---
author: "jafshin"
date: "26/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(readr)
library(ggplot2)
library(purrr)
library(sf)
```

```{r data preparation}

test2 <- st_read("../outputs/Oct21/decisions/output_decision_D15.csv")
decisions <- list.files("../outputs/Oct21/decisions", pattern=".csv", full.names=T) %>%
    map_dfr(read_csv)

# merging the decisions
score <- read_csv("../outputs/Oct21/score_summary.csv")
```

## Plotting the score change

TODO: think about the interpretation of the score as well! 
might have interesting insights such as the jump from 15 to 25 is much bigger than 35 to 45

```{r cars}
ggplot(data = score, aes(x=density, y=score)) +
  geom_line()
```

## Number of open destinations

```{r number of open per density}

decisions %>% 
  group_by(dest_type_id,density) %>% 
  summarise(total_open = sum(num_open)) %>% 
  ungroup()  %>%
  ggplot(aes(x=as.character(dest_type_id),y=total_open)) +
  geom_line(aes(colour=as.factor(density), group=as.factor(density))) + scale_colour_hue()

```

## Number of open destinations

```{r number of open per type}

decisions %>% 
  group_by(dest_type_id,density) %>% 
  summarise(total_open = sum(num_open)) %>% 
  ungroup()  %>%
  ggplot(aes(x=as.character(density),y=total_open)) +
  geom_line(aes(colour=as.factor(dest_type_id), group=as.factor(dest_type_id))) +
facet_wrap(~dest_type_id, scales="free_y")+ scale_colour_hue()

```

## Destination specific

### 1001

```{r number open}
decisions %>% 
  filter(dest_type_id==1001) %>% 
  group_by(density) %>% 
  summarise(total_open = sum(num_open)) %>% 
  ungroup()  %>%
  ggplot(aes(x=as.character(density),y=total_open)) +
  geom_col() 
```


```{r number open}
decisions %>% 
  filter(dest_type_id==1001) ->test %>% 
  group_by(density) %>% 
  summarise(total_open = sum(num_open)) %>% 
  ungroup()  %>%
  ggplot(aes(x=as.character(density),y=total_open)) +
  geom_col() 
```