---
author: "jafshin"
date: "26/10/2020"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(readr)
library(ggplot2)
library(purrr)
library(sf)
library(tibble)
library(stringr)

```

## Processing outputs:

This code goes over the optimistation output files (sqlites) and extracts our key measure from them.
The output measures are number of open destinations, % of unused capapcity and % unserved population.
Outputs tables will be written into csv files at ./processedOutputs/ directory.

```{r}

# Number of open destinations

exrtactTidyCols <- function(dataFrame ,col_string){
  df <- dataFrame %>%
    st_drop_geometry() %>% 
    group_by(density) %>% 
    select(starts_with(col_string)) %>%
    summarise_all(sum) %>% 
    column_to_rownames(var = "density") %>% 
    t() %>% 
    as.data.frame() %>% 
    rownames_to_column("destType") %>% 
    mutate(destType =stringr::str_remove(df$destType, paste0(col_string,"_"))) %>% 
    pivot_longer(!destType, names_to = "density", values_to = col_string)
  return(df)
}

processOutput<- function(output_dir,total_population){
  decisions <- list.files(paste0(output_dir,"decisions"), pattern="^.*sqlite$", 
                          full.names=T) %>%
      map_dfr(~st_read(.x,layer = "decision", quiet=T) %>% 
                mutate(filename=gsub(".sqlite","", basename(.x))))
  pixels <- list.files(paste0(output_dir,"decisions"), pattern="^.*sqlite$", 
                       full.names=T) %>%
      map_dfr(~st_read(.x,layer = "pixels", quiet=T) %>% 
                mutate(filename=gsub(".sqlite","", basename(.x))))
  
  colStrs <- c("num_dest", "pop_total", "pop_remaining","not_served_by")
  
  outputLong <- exrtactTidyCols(decisions, colStrs[1]) %>%
    left_join(exrtactTidyCols(decisions,colStrs[2]),by=c("destType","density")) %>% 
    left_join(exrtactTidyCols(decisions,colStrs[3]),by=c("destType","density")) %>% 
    left_join(exrtactTidyCols(pixels,colStrs[4]),by=c("destType","density")) %>% 
    mutate(unusedCapacity=100*((pop_total*1.5)-(pop_total-pop_remaining))/(pop_total*1.5)) %>% 
    mutate(unservedPop=100*not_served_by/total_population)
  
  outputWide <- outputLong %>% 
    dplyr::select(destType, density, num_dest, unusedCapacity, unservedPop) %>% 
    pivot_wider(names_from=density, 
                 values_from=c(num_dest, unusedCapacity, unservedPop))
  return(outputWide)
}

output_dir <- "../outputs/Exp3_Dec7_1017/"
total_population <- 60000
experiment3 <- processOutput(output_dir, total_population)
write_csv(experiment3, "processedOutputs/exp3_OutputTable.csv")

output_dir <- "../outputs/Exp3_withDiversity_Feb1_1734/"
total_population <- 60000
experiment3_withDiversity <- processOutput(output_dir, total_population)
write_csv(experiment3_withDiversity, 
          "processedOutputs/exp3_withDiversity_OutputTable.csv")

output_dir <- "../outputs/Exp4_Dec07_0900/"
total_population <- 30000
experiment4 <- processOutput(output_dir, total_population)
write_csv(experiment4, "processedOutputs/exp4_OutputTable.csv")

```